### ISSUE TITLE
PostgreSQL 15 the default permissions of the public schema have been modified

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-issues#2015]
### Description 
When installing Postgresql Bitnami Helm with PostgreSQL version 15 with the FusionAuth helm chart, the following error was thrown in the FusionAuth pod logs.

`Cause: org.postgresql.util.PSQLException: ERROR: permission denied for schema public`

With Postgresql 15, the default permissions for a public schema have been modified. Therefore, the correct permissions will have to be granted to the `fusionauth` for Postgresql 15. 

Since the `fusionauth` user is the one to create the database tables, I believe we would have to add this line:

`GRANT ALL ON SCHEMA public TO fusionauth;`

### Affects versions
1.40.2
It should affect all versions because FusionAuth is not currently on Postgresql 15. 

### Expected behavior
The fusionauth user should have adequate permissions to create the database tables

[POSTGRESQL ERROR: PERMISSION DENIED FOR SCHEMA PUBLIC](https://www.cybertec-postgresql.com/en/error-permission-denied-schema-public/)

### Tasks
- [X] Update maint. mode to work with postgresql 15. 
- [ ] ~~Update doc steps that demonstrate how to manually provision the schema~~
- [ ] Review dev setup 
- [X] Modify savant database-plugin
- [X] Bump savant database-plugin dependency in fusionauth-app.

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS
 - Browser + version: Chrome
 - PostgresSQL Helm Chart 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1944
- https://github.com/savant-build/database-plugin/pull/2

**Comment by mooreds** [comment]
See also https://github.com/FusionAuth/fusionauth-issues/issues/1944 which may be a duplicate.

**Comment by jaywood128** [comment]
Duplicate of #1944

**Comment by robotdan** [comment]
Internal:
- https://github.com/inversoft/inversoft-maintenance-mode/pull/2

**Comment by mmanes** [comment]
Internal:
Docs at https://fusionauth.io/docs/v1/tech/installation-guide/fusionauth-app#database-schema call out setting the DB owner. No need to update.
