### ISSUE TITLE
Digital Ocean 1-click provisioning fails

### ISSUE THREAD

**Issue by mmanes** [FusionAuth/fusionauth-issues#2051]
Deploying FusionAuth from the DigitalOcean Kubernetes Marketplace fails without error due to the following issues:
* Chart deployed a PostgreSQL 15 instance, which is currently unsupported by FA.
- https://github.com/digitalocean/marketplace-kubernetes/pull/425
* Chart relied on relative paths for values yaml files.
- https://github.com/digitalocean/marketplace-kubernetes/pull/427

***Tasks***:
- [x] Update marketplace description page

- [x] Test 1-click deployment once DO merges PR
- [x] Verify/update marketplace documentation page
