### ISSUE TITLE
Documentation project - Quickstarts and integrations

### ISSUE THREAD

**Issue by andrewpai** [FusionAuth/fusionauth-issues#2213]
### Description
We are writing or refreshing a number of articles and posts around integrations and quickstarts. We're also taking the opportunity to move them over to a new doc tech stack.

See the `Documentation Project - tech integrations and more` document for available items. The items are ranked in priority order.

### Work items
Here are the outstanding items as of the creation of this ticket. Be sure to check the Documentation Project document for the most up-to-date status of each item (only pick up an item if the Status is `Unauthored` or `Needs touch up`, and does not have an Owner assigned).

#### Webapps
Here's [an example](https://fusionauth.io/docs/v1/tech/tutorials/integrate-ruby-rails) of what these should look like.
- [ ] PHP
- [ ] PHP / Symfony
- [ ] JavaScript / Gatsby (Needs touch up)
- [ ] PHP / Joomla (Needs touch up)
- [ ] JavaScript / NodeBB (Needs touch up)
- [ ] Ruby / Hanami

#### SPA
- [ ] JavaScript / React (Needs touch up)
- [ ] JavaScript / Vue.js (Needs touch up)

#### Native/Mobile
- [ ] Kotlin / Android
- [ ] iOS

#### Backend/API
- [ ] Ruby on Rails (Needs touch up)
- [ ] Go (Needs touch up
- [ ] C# / .NET
- [ ] #2283
- [ ] Java / Spring
- [ ] Java / Dropwizard
- [ ] Ruby / Sinatra

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by andrewpai** [comment]
Closing, as this work is being tracked elsewhere now.
