### ISSUE TITLE
Update deps for 1.56.0 

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2960]
### Description

Update any 3rd party dependencies that have updates or security updates.

- [x] `ch.qos.logback:logback-core` `1.5.6` -> `1.5.16`
- [x] `org.primeframework:prime-mvc` `4.27.0` -> `4.29.2`
- [x] `org.graalvm.polyglot:polyglot` `22.3.3` -> `24.1.2`
- [x] `org.graalvm.js:js` `22.3.3` -> `24.1.2`
- [x] `com.inversoft:inversoft-cache` `0.6.0` -> `0.6.1`
- [x] `com.inversoft:inversoft-api-authentication` `0.29.0` -> `0.30.0`

### Tasks
- Clear up https://github.com/FusionAuth/fusionauth-app/security/dependabot

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2873

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).
