### ISSUE TITLE
Limit Elasticsearch pagination

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#494]
### Description 
Elasticsearch has a max pagination window and FusionAuth needs to validate the paginated request before this threshold is reached. 

Like many search engines, we can just limit the results to be paginated. 

For example : `Displaying 1 to 25 of 20,002` but only provide buttons for pages that we can access. Once you reach the end you'll have to provide some search criteria to reduce the size of the result set.

### Steps to reproduce
1. Load up > 10k users
2. Use the User Search page, set page size to 500
3. Page through until you pass 10k

### Expected behavior
No explosions. 

### Screenshots
N/A

### Additional context
https://discuss.elastic.co/t/paginating-result-set-greater-than-10000-with-aggregations-possible-options/119673

This will affect the search users in the UI, the delete by search query and the search API.

We can likely work around this limitation in the delete by search by re-executing the search query before we reach the pagination the threshold. 

The search API and the user search UI will be limited to this result set size. We just need to limit the API before we reach this threshold so we can communicate this limitation to the API caller.

In version 7 of Elasticsearch, by default the Search API will only return up to 10,000 hits.  `track_total_hits` can be added to the request to get the actual hits back, presumably this is a performance enhancement. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html

We could update the doc and UI to indicate one we are over 10k there could be additional hits. 

We would just then also want to confirm that on our total report, we have an accurate user count available. 

See also the `max_result_window` configuration to see how this is related, I believe this also default to 10k. 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1086
- https://github.com/FusionAuth/fusionauth-issues/issues/1974
- https://github.com/FusionAuth/fusionauth-issues/issues/2358

### Tasks
- [x] Document the new `limit` parameter on Bulk User API
- [x] Add documentation on how to use searchAfter in API
- [x] Document the new `nextResults` request and response parameter. 
- [x] Add documentation for behavior on Admin Users and Entities extended pagination
- [x] Scour the current docs to find all places that mention the 10,000 limit. There are several, including a SCIM guide.
        - https://fusionauth.io/docs/v1/tech/core-concepts/scim#the-fusionauth-scim-workflow

### Workaround
- https://github.com/FusionAuth/fusionauth-example-scripts/tree/master/full-user-search

### Release Notes
Enhance the User and Entity Search APIs to paginate beyond 10,000 results. The Search API response will now include a `nextResults` value that can be used to ask for the next set of search results which enables the API to paginate through the entire available result set.
  ** See the link:/docs/v1/tech/apis/entity-management/entities#search-for-entities[Entity Search APIs] and link:/docs/v1/tech/apis/users#search-for-users[User Search APIs] for API details.

**Comment by patrickvalle-transloc** [comment]
This would be a great ticket to get in- as it is, when running ES 7, I can't get an accurate count of the total # of users in FusionAuth via the FusionAuth API.

**Comment by robotdan** [comment]
Thanks for the feedback @patrickvalle-transloc.

We may not actually change the query response to request the total number of hits. I suppose we could make this a configuration option, but there will be a performance hit to request the total hit count. 

Currently the UI will change the description of the pagination when the hit count is equal to 10k to indicate there may be more results. 

To get the total user count, use the Total Report, `Reports > Totals`.

**Comment by ChakshuGautam** [comment]
I am trying to get all the phone numbers of users for a group, to send them notifications. The number of users are in the range of 1-2 Million. I have a couple of questions,
1. Is FA the best place to have such time of queries or should I create a pipeline and publish updates elsewhere?
2. Is there an API planned which can allow me to get users data with specific fields - name, phone number or just the data field?
3. Is it advisable to modify elastic search to index only certain properties and get results directly from there without fetching the database - Bypassing FA APIs? (I have updated the `index.max_result_window` to the number of results that I am expecting)

**Comment by mooreds** [comment]
@ChakshuGautam those are great questions, but GitHub issues are really for issues. For general questions, [please ask in the forum](https://fusionauth.io/community/forum/), unless you have a support contract, in which case you should [open a support ticket](https://fusionauth.io/community/forum/topic/458/i-m-a-customer-how-do-i-open-a-support-ticket).

**Comment by robotdan** [comment]
Some of the fixes from https://github.com/FusionAuth/fusionauth-issues/issues/1086 may help here as well.

**Comment by bhalsey** [comment]
Increasing `max_result_window` on the index would allow us to push the 10k limit to a higher value, but with increase memory and cpu consumption.  The recommended solution from ElasticSearch is to provide the `search_after` parameter with values from the last document on a list of results:
https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/306
